### ISSUE TITLE
Sensor unavailability functionality

### ISSUE THREAD

**Issue by aleksandro-peter** [tcslab/iotlabmeasurements#1]
For a way to tell the database that the measurement that was supposed to be taken wasn't taken for some reason (i.e. the experiment tried to take a value from a sensor but it was down). I'm thinking that it could be the same as the insert but instead of measurement_value I could insert  a error message.

**Comment by aligit** [comment]
This has been implemented in commit 50dc552. Check the last part of README.md for further explanation.

By specifying the resource_id you can verify the availability status of a resource.  If the specified resource is not available you will get a false message and true otherwise.
