### ISSUE TITLE
Additional calls

### ISSUE THREAD

**Issue by aleksandro-peter** [tcslab/iotlabmeasurements#4]
Get LAST measurement by experiment_id and resource_id

**Comment by aligit** [comment]
Dear Panagiotis,
This has been resolved on commit  [cd101f8](https://github.com/tcslab/iotlabmeasurements/tree/cd101f8a5976cf7474423903874ea22b72bc3ae7) on the master branch.
However due to technical issues it has not been yet deployed. Hopefully it will be by Monday.
